# Generated by Django 6.0 on 2026-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='sections',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
